import Navbar from "../components/server/sesion";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body>
        <Navbar />
        <div className="bg-[#B4C5E4]">
          {children}
        </div>
      </body>
    </html>
  );
}
